[build]
# target = ["riscv64gc-unknown-none-elf", "loongarch64-unknown-none"]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-C","link-arg=-Tsrc/riscv/linker_script/linker.ld",
  "-C","force-frame-pointers=yes",
]

[target.loonarch64-unkonwn-none]

[term]
color = "always"
